language: php

branches:
  only:
  - UnitTest

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 5.2
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
  
before_script:
  - sudo apt-get update
  - sudo aptitude safe-upgrade
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - sudo mv phpunit.phar /usr/local/bin/phpunit
  - /usr/local/bin/phpunit --self-update

script:
  - /usr/local/bin/phpunit --version
  - /usr/local/bin/phpunit --configuration phpunit.xml --coverage-text