language: php

branches:
  only:
  - UnitTest

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 5.2
    - php: hhvm
  
before_script:
  - sudo update-ca-certificates
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - sudo mv phpunit.phar /usr/local/bin/phpunit
  - /usr/local/bin/phpunit --self-update
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction

script:
  - /usr/local/bin/phpunit --version
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
   - php vendor/bin/coveralls -v